name: build-gitx

on: [pull_request]

jobs:
  buildGitx:
    name: build-gitx
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/Xcode_12.2.app
      - name: pre build
        run: cd External/objective-git && script/bootstrap && script/update_libgit2 && cd ../..
      - name: Build project
        run: xcodebuild -workspace GitX.xcworkspace -scheme GitX archive | xcpretty
      - name: Xcodebuild Action
        uses: sersoft-gmbh/xcodebuild-action@v1.1
        with:
          project: GitX.xcodeproj
          scheme: GitX
          configuration: Debug
          action: test

